#!/usr/bin/awk -f

{ 
	if((NR%2)==0){
		for(i=1;i<=NF;i++) {
			if((i%2)==0) {
				gsub(/./, "_", $i)
				printf $i " "
			} else printf $i
		}
		print ""
	} else {
		for(i=1;i<=NF;i++) {
			gsub(/[A-Z]/, "*", $i)
			printf $i
		}
		print ""
	}
}
