#!/usr/bin/awk -f
BEGIN {
	n=0
}

{ 
	for(i=1;i<=NF;i++) {
		if($i ~ /^[0-9]+$/) {
			ln=(length($i)-2)
			key=substr($i, ln, 3)
			#key=($i%1000)
			tab[key]++
		}
  	}
  	n+=NF
}

END { 
	system(":>tmp")
	printf "Klucz\tKrotnosc\tCzestotliwosc\n"
	for (i in tab) {
		print i"\t"tab[i]"\t\t"tab[i]/n >> "tmp"
	}
	system("sort -k2rn tmp | head -n15 | sort -k1")
}
	

